version: "3.8"
services:
  web:
    build: ./react-login-signup
    ports:
      - 5050:5050
    restart: unless-stopped
  node:
    restart: always
    build: ./node-login-signup
    ports:
      - 7070:7070
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: