version: '3'
services:
  web:
    build:
      context: ./react-login-signup
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    restart: unless-stopped
  node:
    restart: always
    build: ./node-login-signup
    ports:
      - 7070:7070
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: