version: '3'
services:
  web:
    container_name: react-prod
    build:
      context: ./react-login-signup
      dockerfile: Dockerfile.prod
    ports:
      - 8888:80
    network_mode: "host"
    restart: unless-stopped
  node:
    container_name: node-prod
    restart: always
    build: ./node-login-signup
    ports:
      - 7070:7070
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: