version: '3.8'
services:
  web:
    container_name: react-prod
    build: ./react-login-signup
    ports:
      - 8080:80
    network_mode: "host"
    restart: unless-stopped
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - dbData:/data/db
  node:
    container_name: node-prod
    restart: unless-stopped
    build: ./node-login-signup
    ports:
      - 7070:7070
    links:
      - db
    volumes:
      - ./:/code
volumes:
 dbData: